export * from './AboutMe'
export * from './EfeitoDigitando'
export * from './Footer'
export * from './Formulario'
export * from './Header'
export * from './Projetos1'
export * from './Projetos2'
export * from './Skills'